name: CD

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Incrementar versión
        run: |
          VERSION=$(grep -oP 'AppVersion-\K[0-9]+' README.md)
          NEW_VERSION=$((VERSION + 1))
          DATE=$(date '+%Y-%m-%d %H:%M:%S')

          sed -i "s/AppVersion-$VERSION/AppVersion-$NEW_VERSION - $DATE/" README.md

      - name: Guardar README
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "chore: incrementar versión" || echo "Sin cambios"
          git push

  job2:
    needs: job1
    runs-on: self-hosted

    steps:
      - name: Comparar secret con variable local
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}
        shell: powershell
        run: |
          if ($env:TOKEN -eq $env:LOCAL_PROD_TOKEN) {
            Write-Host "Coinciden "
          } else {
            Write-Host "No coinciden "
            exit 1
          }